### ISSUE TITLE
config.json Syntaxfehler

### ISSUE THREAD

**Issue by TurboSasch** [Phil0xFF/homebridge-lupus-security#1]
Hi!

is it normal, that only arm and disarm is show in Home App?? I thought, there are more options as arm, disarm and night or so.

regards
Sascha

**Comment by Phil0xFF** [comment]
Hi, currently you can only switch the status of the area 1 alarm to home mode, arm and disarm. 
The next goal is to implement the correct alarm system accessories instead of the switches. I plan to release an update for the plugin until November. 
The plan is to make it look [something like the picture here](https://www.eimsig.de/sites/default/files/2019-10/landingpage-phone-min.png).

**Comment by TurboSasch** [comment]
Ah fantastic news. Nice :-). That´s a good plan. You make a really good job!

**Comment by Phil0xFF** [comment]
I used my Saturday to rewrite the entire plugin. You can now use the default homekit security accessories. Including automatic import of all Lupus contact sensors.
I have put instructions in the README on how to update to the new version.
Feel free to ask questions here, have fun!

**Comment by TurboSasch** [comment]
Really good job! I deinstall now the old version and delete all values from config, but now after install the new version i cannot save the new platform as i wrote my name, pass and host adress.

Here is the fail:

"Failed to load config: Plugin alias could not be determined"

**Comment by Phil0xFF** [comment]
Could you send me your config file? It should look something like this.
```json
{
    "bridge": {
        "name": "Homebridge 2329",
        "username": "0E:D5:6C:87:23:29",
        "port": 51652,
        "pin": "650-68-955",
        "advertiser": "bonjour-hap"
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "platform": "config"
        },
        {
            "lupusUrl": "http://127.0.0.1",
            "lupusUsername": "admin",
            "lupusPassword": "password",
            "platform": "HomebridgeLupusSecurity"
        }
    ]
}

**Comment by TurboSasch** [comment]
{
	"bridge": {
		"pin": "566-72-291",
		"port": 51546,
		"username": "0E:76:E3:C5:BD:48",
		"name": "Homebridge AD5A",
		"bind": [
			"eth0"
		]
	},
	"platforms": [{
			"name": "Config",
			"port": 8581,
			"auth": "form",
			"theme": "auto",
			"tempUnits": "c",
			"lang": "de",
			"platform": "config"
		},
		{
			"lupusUrl": "http://192.168.178.112",
			"lupusUsername": "admin",
			"lupusPassword": "password",
			"platform": "homebridgelupussecurity"
		},
		{
			"name": "Meross",
			"garageDevices": [{
				"name": "Garagentoröffner"
			}],
			"platform": "Meross",
			"username": "xxxxx@gmx.de",
			"password": "xxxx"
		},
		{
			"devices": [{
				"name": "Dreambox DM900 UHD",
				"hostname": "192.168.178.45",
				"port": 80,
				"username": "root",
				"password": "dreambox",
				"bouquet": "Sky HD",
				"updateInterval": 0,
				"offWhenUnreachable": true
			}],
			"platform": "Dreambox"
		},
		{
			"people": [{
					"name": "Sascha",
					"target": "192.168.178.29",
					"enableCustomDns": false,
					"type": "occupancy"
				},
				{
					"name": "Dani",
					"target": "192.168.178.27",
					"type": "occupancy"
				},
				{
					"name": "Catarina",
					"target": "192.168.178.183",
					"type": "occupancy"
				},
				{
					"name": "Kilian",
					"target": "192.168.178.43",
					"type": "occupancy"
				}
			],
			"anyoneSensor": true,
			"anyoneSensorName": "Jemand anwesend",
			"anyoneSensorType": "occupancy",
			"nooneSensor": true,
			"nooneSensorName": "Niemand anwesend",
			"nooneSensorType": "occupancy",
			"platform": "PeoplePro"
		},
		{
			"devices": [{
				"name": "My LG TV",
				"ip": "192.168.178.47",
				"mac": "B0:37:95:F2:A8:3B",
				"pollingInterval": 5,
				"volumeLimit": 100,
				"volumeControl": "slider",
				"channelControl": true
			}],
			"platform": "webostv"
		},
		{
			"units": "ca",
			"interval": 1,
			"stations": [{
				"nameNow": "Ettelscheid Wetterstation ",
				"service": "weatherunderground",
				"key": "f88a472b6f23472e8a472b6f23d72eba",
				"locationGeo": [
					50.53381475,
					6.443035419558965
				],
				"locationCity": "Schleiden ",
				"stationId": "ISCHLE54",
				"language": "de",
				"compatibility": "home",
				"forecast": [
					"In 3 days"
				],
				"conditionCategory": "detailed",
				"now": true,
				"extraHumidity": true
			}],
			"platform": "WeatherPlus"
		},
		{
			"options": {
				"username": "xxxx@gmx.de",
				"password": "xxxx",
				"accessId": "3gymhcc4bj9hksspj6f6",
				"accessKey": "d41c15615eb24c38bd2f056640906cd7",
				"lang": "de",
				"projectType": "2",
				"appSchema": "smartlife",
				"countryCode": 49,
				"debug": false
			},
			"name": "TuyaPlatform",
			"platform": "TuyaPlatform",
			"_bridge": {
				"username": "0E:D9:82:63:C0:94",
				"port": 50834
			}
		},
		{
			"name": "Homebridge Panasonic AC Platform",
			"email": "xxxx@gmx.de",
			"password": "xxx",
			"exposeOutdoorUnit": true,
			"debugMode": false,
			"platform": "Panasonic AC Platform"
		}
	],
	"accessories": [{
		"name": "Pihole",
		"auth": "6091676e4bfa5f3f9efa23d895ff99bed3fa8b516386b213b24cb941c90c39c2",
		"ssl": false,
		"rejectUnauthorized": true,
		"host": "localhost",
		"port": 80,
		"baseDirectory": "/admin/",
		"time": 0,
		"reversed": false,
		"logLevel": 1,
		"accessory": "Pihole"
	}],
	"disabledPlugins": [
		"homebridge-z2m",
		"homebridge-hue",
		"homebridge-camera-ui",
		"homebridge-smartglass",
		"@milo526/homebridge-tuya-web",
		"homebridge-shelly-switch",
		"homebridge-camera-ffmpeg",
		"homebridge-panasonic-ac-platform"
	]
}

**Comment by Phil0xFF** [comment]
Thanks, can you try to write the platform name with capitalized letters? Like this "HomebridgeLupusSecurity"

**Comment by TurboSasch** [comment]
I found the issue! The name of the platform was wrong.

{
	"bridge": {
		"pin": "566-72-291",
		"port": 51546,
		"username": "0E:76:E3:C5:BD:48",
		"name": "Homebridge AD5A",
		"bind": [
			"eth0"
		]
	},
	"platforms": [{
			"name": "Config",
			"port": 8581,
			"auth": "form",
			"theme": "auto",
			"tempUnits": "c",
			"lang": "de",
			"platform": "config"
		},
		{
			"lupusUrl": "http://192.168.178.112",
			"lupusUsername": "admin",
			"lupusPassword": "password",
			"platform": "**homebridgelupussecurity**"
		}

**Comment by Phil0xFF** [comment]
It looks like there are some issues when adding a few sensors (16 in my case). I will have a look into that tomorrow. #2
